name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GCR_HOSTNAME: gcr.io/${{ secrets.PROJECT_ID }}
  SERVICE_NAME: go-api-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Build
        run: |
          go build -o app main.go

      - name: Build and push Docker image
        run: |
          docker build -t go-app .
          echo "${{ secrets.SERVICE_ACCOUNT }}" | docker login -u _json_key --password-stdin https://us-west1-docker.pkg.dev/giiku5
          docker push go-app

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image go-app \
            --platform managed \
            --region us-west1 \
            --allow-unauthenticated
