name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE: asia.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}
jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ env.SERVICE_NAME }}
            kou7306/my-image

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u kou7306 --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker Push
        run: |-
          gcloud auth configure-docker \
            --quiet \
            --project=${{ env.PROJECT_ID }} \
            --push=true

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --quiet \
            --project=${{ env.PROJECT_ID }} \
            --region=us-west1 \
            --image=kou7306/my-image
